# Zookeeper hosts for Kafka Manager
# Replace with your actual Zookeeper connection string, which could be a comma-separated list of hosts if you have a Zookeeper ensemble
# kafka-manager.zkhosts="172.21.0.2:2181"

# Set the application name
play.crypto.secret="test"

# Port for the application to run on
play.server.http.port=9000

# Authentication (Optional)
# Uncomment and set the following lines if you want to enable authentication
#kafka-manager.auth.enabled=true
#kafka-manager.auth.username="admin"
#kafka-manager.auth.password="password"
#kafka-manager.auth.user="admin:password"

# Basic Authentication (Optional)
# Uncomment and set the following lines if you want to enable basic authentication
#play.http.auth.basic.enabled=true
#play.http.auth.basic.realm="Kafka Manager"
#play.http.auth.basic.user="admin"
#play.http.auth.basic.password="password"

# Logger settings (Optional)
logger.root=INFO
logger.play=INFO
logger.application=INFO
